# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kakani.jonathan@gmail.com
author_name: Paul-Jonathan2005
contract_name: gameshub_contract
deployment_language: python
preset_name: production
project_name: GamesHub

